### ISSUE TITLE
Death Star BOT - Bug

### ISSUE THREAD

**Issue by rohid2000** [rohid2000/tsom-bot#104]
System.NullReferenceException: Object reference not set to an instance of an object.

`The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at tsom_bot.Commands.Helpers.TicketTrackerCommandHelper.SaveGuildData() in /home/xrdpuser/bot-repo/tsom-bot/tsom-bot/Commands/Helpers/TicketTrackerCommandHelper.cs:line 34
   at tsom_bot.Commands.Helpers.TimerHelper.SendSaveGuildData(DiscordClient client, Int32 adjustedInterval, Boolean runOnLaunch) in /home/xrdpuser/bot-repo/tsom-bot/tsom-bot/Commands/Helpers/TimerHelperTicketTracker.cs:line 128
   at tsom_bot.Commands.Helpers.TimerHelper.SyncGuildSaveCommand(DiscordClient client, Boolean runOnLaunch) in /home/xrdpuser/bot-repo/tsom-bot/tsom-bot/Commands/Helpers/TimerHelperTicketTracker.cs:line 58
   at tsom_bot.Commands.Helpers.TimerHelper.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in /home/xrdpuser/bot-repo/tsom-bot/tsom-bot/Commands/Helpers/TimerHelperTicketTracker.cs:line 19
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aborted
`

**Comment by rohid2000** [comment]
@YannickdeZwart, called it. The problem is that it takes too long to connect with the ComLink, that is why a timeout appears sometimes and the BOT goes offline. We'll need to look for a permanent fix (hosting ComLink on Azure? Research)
